[2021-03-23 14:48:41,835] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: data_prep_and_process.data_preperation 2021-03-21T00:00:00+00:00 [queued]>
[2021-03-23 14:48:41,846] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: data_prep_and_process.data_preperation 2021-03-21T00:00:00+00:00 [queued]>
[2021-03-23 14:48:41,847] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 14:48:41,847] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-03-23 14:48:41,847] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 14:48:41,856] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): data_preperation> on 2021-03-21T00:00:00+00:00
[2021-03-23 14:48:41,859] {standard_task_runner.py:52} INFO - Started process 40986 to run task
[2021-03-23 14:48:41,871] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_prep_and_process', 'data_preperation', '2021-03-21T00:00:00+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/var/folders/yw/952dv3rd0332_2c7vqyq34vc0000gp/T/tmph6blmebu', '--error-file', '/var/folders/yw/952dv3rd0332_2c7vqyq34vc0000gp/T/tmpn8o_mlmm']
[2021-03-23 14:48:41,874] {standard_task_runner.py:77} INFO - Job 20: Subtask data_preperation
[2021-03-23 14:48:46,925] {logging_mixin.py:104} INFO - Running <TaskInstance: data_prep_and_process.data_preperation 2021-03-21T00:00:00+00:00 [running]> on host FACT-LAP-135.local
[2021-03-23 14:48:51,969] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=skadhithya95@example.com
AIRFLOW_CTX_DAG_OWNER=adhithya
AIRFLOW_CTX_DAG_ID=data_prep_and_process
AIRFLOW_CTX_TASK_ID=data_preperation
AIRFLOW_CTX_EXECUTION_DATE=2021-03-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-21T00:00:00+00:00
[2021-03-23 14:48:51,971] {logging_mixin.py:104} INFO - 1
[2021-03-23 14:48:51,972] {logging_mixin.py:104} INFO - hello
[2021-03-23 14:48:51,974] {python.py:118} INFO - Done. Returned value was: None
[2021-03-23 14:48:51,981] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=data_prep_and_process, task_id=data_preperation, execution_date=20210321T000000, start_date=20210323T091841, end_date=20210323T091851
[2021-03-23 14:48:51,999] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-23 14:48:52,036] {local_task_job.py:146} INFO - Task exited with return code 0
